# Generated by Django 3.2.6 on 2021-08-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalApp', '0002_rename_medicaldetails_medicinedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
